//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenaProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Form
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Lütfen form adını giriniz")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Lütfen form tanımlamasını giriniz")]
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
